### ISSUE TITLE
country code 

### ISSUE THREAD

**Issue by saltsoftdrink** [theolm/WhatsAppNoContact#11]
Add option to select default country code

**Comment by theolm** [comment]
@saltsoftdrink This is a very good idea. I see two viable solutions for this issue:

1. Create a config activity config to set the default code;
2. After the first, we save the country code and use it to autofill the subsequent launches. 

The 2 seem to have better usability, but 1 gives room for more configs later.

How do you see this feature?

**Comment by ihatemakinganaccount** [comment]
I approve both of this app as well as this suggestion.

**Comment by theolm** [comment]
I'm already working on a solution for that, and should be complete in the next week.

It's a settings screen where the user can select the default country.
The default is no country code, but once selected it will stay selected for all the subsequent launches.

**Comment by theolm** [comment]
The #12 closes this issue.
A settings page was added to select the country.
The update should be available on the release page in a few minutes and on the F-droid in 3 or 4 days.

Please report bugs or errors in the translation.
