### ISSUE TITLE
Change icon 

### ISSUE THREAD

**Issue by mvevitsis** [theolm/WhatsAppNoContact#15]
The icon is a bit *too* similar to Whatsapp, so can be opened accidentally.

**Comment by theolm** [comment]
It's actually the same icon. lol

I'm ok with changing the icon, but I'm no designer so I don't have the skills to do it.
I'll try something using ChatGPT, otherwise, we will have to wait for some contribution.

**Comment by pisoj** [comment]
I think changing the **background color** would be fine.
