### ISSUE TITLE
Running chat in WhatsApp Business

### ISSUE THREAD

**Issue by Ser1ousSAM** [theolm/WhatsAppNoContact#17]
### Steps to reproduce

I have WhatsApp and WhatsApp Business. There are two different accounts on it.

1) Install WhatsApp and WhatsApp Business
2) In WhatsApp sign in one account
3) In WhatsApp Business sign in the other account
4) Try to input number in Chat app

### Expected behavior

I expected running the WhatsApp chat, but it run the WhatsApp Business chat

### Actual behavior

When I input the number,  I get a WhatsApp Business and corresponding account.

_Maybe I do something wrong or it can be fixed via settings, idk._ 

It could be fine, if you can select WhatsApp app and account by default or optional for running chat

### App version

0.6.0.

### Device

Xiaomi 11 Lite 5G 2109119dg

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
@Ser1ousSAM just to let you know that I'll add a new option under settings so the user can select the destination app (whatsapp OR whatsapp business). This option will only be visible If the user has both apps installed. 

should be available on version 0.7.0 (it will take a few days to update on F-droid)

**Comment by theolm** [comment]
#19 closes this issue
