### ISSUE TITLE
Support for WhatsApp Business

### ISSUE THREAD

**Issue by Seferi** [theolm/WhatsAppNoContact#24]
### Describe your suggested feature

It would be awesome if you could add WhatsApp Business support for it: https://play.google.com/store/apps/details?id=com.whatsapp.w4b 
Thanks. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
@Seferi WhatsApp Business is already supported in the latest release. It should be available in F-Droid soon (it takes a few days to update in the store). The way it works is simple, `open the dialog -> settings (small gear icon) -> select default app -> select WhatsApp business`

**Comment by theolm** [comment]
@GreenMystic What do you mean by `profile`? Is that a WhatsApp Business feature? I have never used the Business app before. 
Please create a new issue explaining how you imagine the feature and I will see what I can do to implement it.

**Comment by theolm** [comment]
Nice!
I have never used this before but looks like a good idea. I'll take a look to see what I need to make the app support it. 

Thanks for the great idea.

**Comment by theolm** [comment]
@GreenMystic I don't think you will be able to use the app in a work profile.
You need to be able to sideload the app, and as far as I can tell, this is not possible in your work profile.

If somehow you manage to do it please share it here so I can write it in the docs.

**Comment by theolm** [comment]
@GreenMystic Nice! I want to make this work. Thanks for the info.
I created a new ticket #28, please follow the issue there.

**Comment by Seferi** [comment]
> @Seferi WhatsApp Business is already supported in the latest release. It should be available in F-Droid soon (it takes a few days to update in the store). The way it works is simple, `open the dialog -> settings (small gear icon) -> select default app -> select WhatsApp business`

Doesn't work for some reason. When I hit the app icon, all I see is this dialog in the picture:

![Screenshot_20240714-103225](https://github.com/user-attachments/assets/fd7a4d48-0bcd-493e-9e3a-32967924996d)

**Comment by theolm** [comment]
Good call. I totally forget about this initial check.

I will push an update today. It will take a few days to be available in fdroid

As a workaround you can install the normal whatapp so you can bypass this dialog and reach the configuration menu where you can select Whatsapp business.
