### ISSUE TITLE
Please add again monochrome app icon

### ISSUE THREAD

**Issue by saltsoftdrink** [theolm/WhatsAppNoContact#25]
### Describe your suggested feature

..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
@saltsoftdrink It should be available in the next release
