### ISSUE TITLE
Accept shared numbers

### ISSUE THREAD

**Issue by JonnyTech** [theolm/WhatsAppNoContact#29]
### Describe your suggested feature

Can the app be listed in the Android share menu so that if I copy or highlight a number then this app is on the list to receive it?

### Other details

Something to do with "intents", but my Android developer skills are not good.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
Sure, this is a great idea.
I'll start working on that.

**Comment by theolm** [comment]
@JonnyTech, I just pushed for the initial implementation of the feature. It is not as simple as I first thought, there are many edge cases where the share may not work. The feature will be available in the next release.

Please report any bugs or improvements.

**Comment by JonnyTech** [comment]
Thank you very much @theolm, I suspected that it would be tricky! Once the build appears on [fdroid](https://f-droid.org/en/packages/dev.theolm.wwc/) then I shall check and provide feedback.

**Comment by JonnyTech** [comment]
Just confirming that it is working as expected in my simple tests. Thanks again.
