### ISSUE TITLE
Add support for telegram and signal

### ISSUE THREAD

**Issue by BholeyKaBhakt** [theolm/WhatsAppNoContact#32]
### Describe your suggested feature

Exactly what the title says...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
For now, this is out of the scope of the app. 
I do not use Signal, and Telegram already has a way to start a chat without using the phone number (username).

Maybe in the future, I can consider this. But for now, I don't plan on adding those features.

**Comment by cyb3rko** [comment]
And in Signal you can already start a chat with any phone number.  
Furthermore there are usernames now in Signal as well.
