### ISSUE TITLE
Make it possible to erase default country code once

### ISSUE THREAD

**Issue by danielleontiev** [theolm/WhatsAppNoContact#34]
### Describe your suggested feature

If I need to enter a phone number with a country code that does not match my default country code, the only option is to tap the code and remove it in the opened settings window. The next time I use the app, the default country code is gone, so I need to go to the settings again and set it back.

It would be nice to be able to erase the country code with backspace or double backspace while keeping the setting intact so that the next time I use the app, the default country code is preserved.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
That's a great idea. 
I'll work on it.

Thanks for the contribution.

**Comment by theolm** [comment]
@danielleontiev Done.
It will be available in the next release.

**Comment by danielleontiev** [comment]
Thank you a lot!

**Comment by danielleontiev** [comment]
Interestingly enough, the feature does not work for me on the latest version of the app. I've tried both f-droid and github release build.

I am on LineageOS 21

**Comment by theolm** [comment]
Interesting. You are right.
Even though the code is in main branch, the F-droid-released version doesn't have it.

I'll take a look at it. Thanks for reporting.

**Comment by JonnyTech** [comment]
I am on the F-droid version and v0.10.0 works correctly as expected - pressing backspace twice with no phone number entered deletes the country code.

**Comment by theolm** [comment]
Oh fuck. I just confirmed the issue.
It only happens in some keyboards. I'm using FUTO keyboard on my personal phone and it doesn't work.
If I change to another keyboard, it works.

@JonnyTech @danielleontiev Thanks for the help.
