### ISSUE TITLE
Country code - add search

### ISSUE THREAD

**Issue by SEVENID** [theolm/WhatsAppNoContact#44]
### Describe your suggested feature

Add search for default country code by country and code. Suggest few on top based on system settings. Technicaly related to #11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
Done.
it will be available in the next release.
