### ISSUE TITLE
Show in share menu/

### ISSUE THREAD

**Issue by vvirtues** [theolm/WhatsAppNoContact#66]
### Describe your suggested feature

When I go to my contacts app and click share, I want it to show up there

### Other details

Currently, I have to copy it then paste through shortcut/homepage, but using the share menu, or even better, the "Connected Apps" thing whatsapp has (where it shows that whatsapp can be used to contact a number). 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by JonnyTech** [comment]
>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

That feature was already requested in #29 and implemented in v0.9.0 - which version are you using?

**Comment by vvirtues** [comment]
0.11.1, but I realize now it doesn't work because Google contacts shared a contact file instead of just the number
