### ISSUE TITLE
history

### ISSUE THREAD

**Issue by mizu-048** [theolm/WhatsAppNoContact#76]
a simple history which keeps the catalog of numbers opened, found or not
ability to clear history or selectively delete from it, or perhaps even add a to contacts

**Comment by theolm** [comment]
Great idea.
This will be my top priority in this repo.

**Comment by theolm** [comment]
@mizu-048 This feature will be released in the next version. Do you mind testing it and providing feedback?

**Comment by mizu-048** [comment]
sure
