### ISSUE TITLE
Remove `DependencyInfoBlock`

### ISSUE THREAD

**Issue by licaon-kter** [theolm/WhatsAppNoContact#85]
### Steps to reproduce

https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8236194006#L1345

```
$ apksigtool parse --json app-release.apk | jq -r '.pairs[].value._type'
APKSignatureSchemeBlock
DependencyInfoBlock
VerityPaddingBlock
```
hmm looks like you have the `DependencyInfoBlock` thing :disappointed: 

Can you add this fix: https://gitlab.com/fdroid/fdroidserver/-/issues/1056#note_1218193185 ?
```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

we'll need a new version, tag, release

### Expected behavior

-

### Actual behavior

-

### App version

0.13.1

### Device

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
Thanks for bringing this up. I'll generate a new version with the fix ASAP.
