### ISSUE TITLE
Fix translations in pr-br and es

### ISSUE THREAD

**Issue by theolm** [theolm/WhatsAppNoContact#89]
### Steps to reproduce

-

### Expected behavior

All string files should have all the translations

### Actual behavior

There are missing strings in Portuguese and Spanish.

### App version

any version

### Device

any

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version.
- [X] I will fill out all of the requested information in this form.

**Comment by theolm** [comment]
Hey @marciozomb13,
can you take this one? It should be easy for you =D

**Comment by marciozomb13** [comment]
> Hey @marciozomb13, can you take this one? It should be easy for you =D

Done pt-br.

**Comment by theolm** [comment]
Thank you. Closing this one.
